import "@/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "@/trpc/react";
import { ThemeProvider } from "@/components/theme-provider";
import { ModeToggle } from "@/components/toggle-theme";
import { Button } from "@/components/ui/button";
import DarkmodeIcon, { ToggleTheme } from "@/components/darkmode-icon";

export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

const Header = () => {
  return (
    <header className="fixed top-0 z-50 flex w-full items-center justify-center border-b border-gray-800/10 bg-white/50 backdrop-blur dark:border-gray-100/10 dark:bg-gray-900/40">
      <div className="flex w-[70%] items-center justify-between py-6">
        <div className="text-2xl font-thin">axai-y</div>
        <ul className="flex w-[45%] justify-end gap-8">
          <li>About</li>
          <li>Portfolio</li>
          <li>Books</li>
          <li>Resume</li>
        </ul>

        <div className="flex gap-3">
          {/* <ModeToggle /> */}
          <ToggleTheme />
          <Button>Github</Button>
          <Button>{`Let's Work`}</Button>
        </div>
      </div>
    </header>
  );
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <ThemeProvider attribute="class" defaultTheme="system" enableSystem>
          <TRPCReactProvider>
            <Header />
            {children}
          </TRPCReactProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
