name: CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

env:
  POSTGRES_URL: "https://fake.com"

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x, 16.x, 18.x] # Test on multiple Node.js versions

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run TypeScript type checking
        run: npm run typecheck
        # Assuming you have a script "typecheck" in your package.json that runs the TypeScript checker

      - name: Run linter
        run: npm run lint
        # Assuming you have a script "lint" in your package.json that runs your linter
